command:
  - "streamlit"
  - "run"
  - "app.py"
  - "--server.address=0.0.0.0"

env:
  - name: DATABRICKS_HOST
    value: "https://adb-984752964297111.11.azuredatabricks.net"
  - name: DATABRICKS_HTTP_PATH
    value: "/sql/1.0/warehouses/148ccb90800933a1"
  - name: DATABRICKS_CATALOG
    value: "welch"
  - name: DATABRICKS_SCHEMA
    value: "demand_planning_demo"
  - name: GENIE_SPACE_ID
    value: "01f10122259c1ae8a5211261bb660afb"
  - name: USE_MOCK_DATA
    value: "false"  
