resources:
  jobs:
    train_and_register_late_risk:
      name: "${var.demo_name}-train-late-risk"
      tasks:
        - task_key: train_register
          notebook_task:
            notebook_path: ${workspace.file_path}/notebooks/05_ml_late_risk
            base_parameters:
              catalog: "${var.catalog}"
              schema: "${var.schema}"
              model_name: "${var.late_risk_model_name}"
              train_lookback_days: "540"
              test_days: "90"
          # Choose an existing cluster policy/cluster id in your environment if preferred.
          new_cluster:
            spark_version: "15.4.x-scala2.12"
            node_type_id: "Standard_DS3_v2"
            num_workers: 2

